# Playbook para instalar e conectar o Nextcloud a uma instância do Onlyoffice
# Variáveis para mudar:
# onlyoffice_url
# jwt_secret

- hosts: nextcloud
  gather_facts: no

  vars:
    config_directory: /root/projects/nextcloud-docker
    application: nextcloud-docker-app-1
    common_user: root
    common_group: root
    onlyoffice_url: https://url-do-onlyoffice-MUDE-ME
    jwt_secret: MUDE-ME

  tasks:
    - name: Install onlyoffice app
      community.docker.docker_container_exec:
        container: "{{ application }}"
        user: www-data
        command: "php occ app:install onlyoffice"
      register: _command_result
      failed_when: "'Could not download app' in _command_result.stdout"
      changed_when: "'already installed' not in _command_result.stdout"
      retries: 3
      delay: 2

    - name: Configure onlyoffice app
      community.docker.docker_container_exec:
        container: "{{ application }}"
        user: www-data
        command: "php occ config:app:set onlyoffice {{ item.name }} --value={{ item.value }}"
      register: _command_result
      failed_when:
        - "'for app onlyoffice set to' not in _command_result.stdout"
        - "'Config value were not updated' not in _command_result.stdout"
      changed_when: "'is now set to' in _command_result.stdout"
      retries: 3
      delay: 2
      loop:
        -
          name: jwt_secret
          value: "{{ jwt_secret }}"
        -
          name: DocumentServerUrl
          value: "{{ onlyoffice_url }}"
        -
          #name: DocumentServerInternalUrl
          #value: "{{ onlyoffice_url }}"
        #-
        #  name: StorageUrl
        #  value: "postgres-postgres-1"
        #-
          name: defFormats
          value: '{\"csv\":\"true\",\"doc\":\"true\",\"docm\":\"true\",\"docx\":\"true\",\"docxf\":\"true\",\"oform\":\"true\",\"dotx\":\"true\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"true\",\"ods\":\"true\",\"odt\":\"true\",\"otp\":\"true\",\"ots\":\"true\",\"ott\":\"true\",\"pdf\":\"false\",\"potm\":\"true\",\"potx\":\"true\",\"ppsm\":\"true\",\"ppsx\":\"true\",\"ppt\":\"true\",\"pptm\":\"true\",\"pptx\":\"true\",\"rtf\":\"true\",\"txt\":\"true\",\"xls\":\"true\",\"xlsm\":\"true\",\"xlsx\":\"true\",\"xltm\":\"true\",\"xltx\":\"true\"}'
        -
          name: customizationChat
          value: false
        -
          name: customizationFeedback
          value: false
        -
          name: customizationHelp
          value: false
        -
          name: customizationToolbarNoTabs
          value: false
        -
          name: customizationTheme
          value: "theme-light"
