networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  postgres:
    external: true
    name: postgres
  redis:
    external: true
    name: redis
  onlyoffice:
    external: true
    name: onlyoffice

services:
  onlyoffice:
    image: systemcrashpoa/nerdseverino:Onlyoffice-8-amd64
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
      - ./volumes/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
      - ./volumes/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice
      - ./volumes/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq
      - ./volumes/onlyoffice/DocumentServer/my_fonts_folder:/usr/share/fonts/truetype/custom
    networks:
      - postgres
      - redis
      - onlyoffice
      - reverse-proxy
