# This file is part of LibreCodeCoop/ansible-docker
#
# Copyright (C) 2022 LibreCode coop <contact@librecode.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
- name: Install required {{ role_name }} packages
  ansible.builtin.include_role:
    name: packages
  vars:
    packages: "{{ fail2ban_packages }}"

- name: Ensure {{ role_name }} deamon is running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Copy route.local action file
  ansible.builtin.copy:
    src: files/etc/fail2ban/action.d/route.local
    dest: /etc/fail2ban/action.d/route.local
    owner: root
    group: root
    mode: '0644'

- name: Copy jail template
  ansible.bultin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart {{ role_name }} service


